config/routes.rb
Rails.application.routes.draw do
  resources :vet_records
  root "home#index"
  resources :dogs
  resources :inventory, controller: 'inventories', as: 'inventory'
  resources :inventory_items
  resources :users do
    patch 'set_role', on: :member, as: :set_role
    patch 'restore', on: :member, as: :restore
  end
  resource :records, only: [:show]
  resources :first_login, only: [:index, :update]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  # Defines the root path route ("/")
  # root "articles#index"
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/register', to: 'users#new'  
  get '/scan', to: 'scan#index', as: 'scan'
  get '/data_export', to: 'data_export#index'
  get 'data_export/download_report'
  # get '/first_login', to: 'admin_approval#index', as: "first_login"
  # patch '/admin_approval/:id', to: 'admin_approval#update', as: 'first_login'
  get '/dashboard', to: 'dashboard#index' 
end

app/models/inventory.rb
class Inventory < ApplicationRecord
    has_paper_trail
    has_many :inventory_items, dependent: :destroy
    

    validates :name, presence: true, uniqueness: true

    PRESCRIPTION_SELECTION = [
        "0 to 2 months",
        "3 to 4 months",
        "5 to 6 months",
        "7 to 8 months",
        "9 to 10 months",
        "11 to 12 months",
        "1 to 3 years",
        "4 to 6 years",
        "7 to 10 years",
        "11 to 15 years",
        "16 to 20 years",
        "20 years and above"
    ]


    def total_quantity
        self.unarchived_items.sum(:quantity)
    end

    # get last price of inventory item
    def last_price
        self.inventory_items.last.price
    end

    def items
        self.unarchived_items
    end

    def unarchived_items
        self.inventory_items.where(archived_at: nil)
    end

    def archive
        self.update(archived_at: Time.now)
    end

    def expired_items
        self.unarchived_items.select { |item| item.expired? }
    end

    def unexpired_items
        self.unarchived_items.select { |item| !item.expired? }
    end

    def prescription
        case
        when self.unarchived_items.empty?
          "No items"
        when self.unexpired_items.any? { |item| item.young? } && self.unexpired_items.any? { |item| item.adult? }
          "Young/Adult"
        when self.unexpired_items.any? { |item| item.adult? }
          "Adult"
        when self.unexpired_items.any? { |item| item.young? }
          "Young"
        end
    end

    def price_range
        return "No items" if self.unarchived_items.empty?
  
        price_min = self.unarchived_items.minimum(:price)
        price_max = self.unarchived_items.maximum(:price)
        
        price_min == price_max ? "₱#{price_min}" : "₱#{price_min} to ₱#{price_max}"
    end

end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  include Authentication
  before_action :set_inventory, only: %i[ show edit update destroy ]
  before_action :set_all_params_downcase, only: %i[ create update ]

  # GET /inventories or /inventories.json
  def index
    @inventories = Inventory.where(archived_at: nil).sort_by(&:created_at).reverse
  end

  # GET /inventories/1 or /inventories/1.json
  def show
    fail
  end

  # GET /inventories/new
  def new
    # inventory new merge with inventory item new
    @inventory = Inventory.new
    @inventory.inventory_items.build
    @unique_names = Inventory.distinct.pluck(:name).compact
    @unique_categories = Inventory.distinct.pluck(:category).compact
    @unique_inventory_types = Inventory.distinct.pluck(:inventory_type).compact
    @prescription_selection = AgeList.pluck(:name,:id).compact
  end  

  # GET /inventories/1/edit
  def edit
    fail
  end

  # POST /inventories or /inventories.json
  def create
    # inventory params except inventory items
    inv_params = inventory_params.except(:inventory_items)
    inventory = Inventory.new(inv_params)
    is_new = inventory.new_record? ? true : false
    item = inventory.inventory_items.new(inventory_params[:inventory_items])

    # binding.pry_remote
    if inventory.save && item.save
      if is_new
        inventory.versions.create!(event: "Create Inventory", whodunnit: "#{current_user.username}")
        notice = "Inventory and Item was successfully created."
      else
        notice = "Item was successfully created."
      end
      
      item.versions.create!(event: "Create Inventory Item", whodunnit: "#{current_user.username}")
      
      redirect_to inventory_index_path, notice: notice
    else 
      redirect_to new_inventory_path, alert: "Error: #{inventory.errors.full_messages.join(', ')}"
    end
  end

  # PATCH/PUT /inventories/1 or /inventories/1.json
  def update
    redirect_to inventory_index_path, alert: "Cannot update inventory"
  end

  # DELETE /inventories/1 or /inventories/1.json
  def destroy
    @inventory.archive
    # @inventory.versions.create!(event: "Archive Inventory", whodunnit: "#{current_user.username}")
    redirect_to inventory_index_path, notice: "Inventory was successfully archived."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inventory
      @inventory = Inventory.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def inventory_params
      params.require(:inventory).permit(
        :name,
        :category,
        :inventory_type,
        :manufacturer,
        inventory_items: [
          :id,
          :quantity,
          :price,
          :expiration_date,
          :age_list_id,
        ])
    end

    def set_all_params_downcase
      params[:inventory][:name].downcase!
      params[:inventory][:category].downcase!
      params[:inventory][:inventory_type].downcase!
      params[:inventory][:manufacturer].downcase!
    end

    
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/views/inventories/_form.html.erb
<%= form_with(model: inventory) do |form| %>
  <% if inventory.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(inventory.errors.count, "error") %> prohibited this inventory from being saved:</h2>

      <ul>
        <% inventory.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :quantity, style: "display: block" %>
    <%= form.number_field :quantity %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :sku, style: "display: block" %>
    <%= form.text_field :sku %>
  </div>

  <div>
    <%= form.label :category, style: "display: block" %>
    <%= form.text_field :category %>
  </div>

  <div>
    <%= form.label :manufacturer, style: "display: block" %>
    <%= form.text_field :manufacturer %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/inventories/_inventory.html.erb
<div id="<%= dom_id inventory %>">
  <p>
    <strong>Name:</strong>
    <%= inventory.name %>
  </p>

  <p>
    <strong>Quantity:</strong>
    <%= inventory.quantity %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= inventory.price %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= inventory.description %>
  </p>

  <p>
    <strong>Sku:</strong>
    <%= inventory.sku %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= inventory.category %>
  </p>

  <p>
    <strong>Manufacturer:</strong>
    <%= inventory.manufacturer %>
  </p>

</div>

app/views/inventories/edit.html.erb
<h1>Editing inventory</h1>

<%= render "form", inventory: @inventory %>

<br>

<div>
  <%= link_to "Show this inventory", @inventory %> |
  <%= link_to "Back to inventories", inventories_path %>
</div>

app/views/inventories/index.html.erb
<div class="inventory_page">
	<div class="col-12 d-flex flex-wrap h-25">
		<div class="col-12 d-flex pe-5" >
			<div class="col-3 h-100 d-flex justify-content-center align-items-center fs-3 border border-primary ms-2 rounded" ></div>
			<div class="col-3 h-100 d-flex justify-content-center align-items-center fs-3 border border-primary ms-2 rounded" ></div>
			<div class="col-3 h-100 d-flex justify-content-center align-items-center fs-3 border border-primary ms-2 rounded" ></div>
			<div class="col-3 h-100 d-flex justify-content-center align-items-center fs-3 border border-primary ms-2 rounded" ></div>
		</div>
	</div>
	<div class="col-12 row g-0 h-75">
		<div class="inventory-container col-12 h-100 px-2" >
			<div class="col-12 p-2 d-flex justify-content-between">
				<div class="my-auto">Inventory Items</div>
				<div>
					<%= form_with url: inventory_index_path, method: :get,omit_nil: true do |f|%>
						<div class="d-flex gap-2 align-items-center">
							<div class="d-flex flex-column">
								<%= f.label "Date range:" %> 
								<%= f.text_field :range, value: params[:range], readonly: true, autocomplete: 'off' %>
							</div>
							<div class="d-flex flex-column">
								<%= f.label "Search:" %> 
								<%= f.text_field :name, value: params[:name], onkeydown: "if (event.keyCode == 13) { this.form.submit(); return false; }" %>
							</div>
							<%= link_to "Reset", inventory_index_path, class: "btn btn-secondary" unless params[:range].blank? || params[:name].blank? %>
							<%= f.submit "Filter", class: "btn btn-primary"%>
						</div>
					<% end %>
					<script type="text/javascript">
						$(function() {

						$('#range').daterangepicker({

    						showDropdowns: true,
							minDate: moment('2022-01-01'),
							maxDate: moment().endOf('day'),
							autoUpdateInput: false,
							locale: {
								cancelLabel: 'Clear',
      							format: 'MMM DD, YYYY'
							},
							ranges: {
							'Today': [moment(), moment()],
							'Yesterday': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
							'Last 7 Days': [moment().subtract(6, 'days'), moment()],
							'Last 30 Days': [moment().subtract(29, 'days'), moment()],
							'This Month': [moment().startOf('month'), moment().endOf('month')],
							'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
							},
							singleDatePicker: true
						});

						$('#range').on('apply.daterangepicker', function(ev, picker) {
							$(this).val(picker.startDate.format('MMM DD, YYYY') + ' - ' + picker.endDate.format('MMM DD, YYYY'));
						});

						$('#range').on('cancel.daterangepicker', function(ev, picker) {
							$(this).val('');
						});

						});
					</script>
				</div>
			</div>
			<div class="table-container col-12 h-100 pb-5 overflow-scroll" >
				<div class="flex-table">
					<div class="row header-row m-1">
						<div class="row">
							<div class="col d-flex">
								<div class="col-2 text-center my-auto">NAME</div>
								<div class="col-2 text-center my-auto">TYPE</div>
								<div class="col-2 text-center my-auto">PRESCRIPTION</div>
								<div class="col-2 text-center my-auto">CATEGORY</div>
								<div class="col-2 text-center my-auto">QUANTITY</div>
								<div class="col-2 text-center my-auto">PRICE</div>
							</div>
							<div class="col-auto header-gap"></div>
						</div>
					</div>
					<% @inventories.each do |inventory| %>
						<div class="row inventory-row m-1" id="inventory-<%= inventory.id %>">
							<div class="row">
								<div class="col d-flex">
									<div class="col-2 text-center my-auto"><%= inventory.name.capitalize %></div>
									<div class="col-2 text-center my-auto"><%= inventory.inventory_type.capitalize %></div>
									<div class="col-2 text-center my-auto"><%= inventory.prescription %></div>
									<div class="col-2 text-center my-auto"><%= inventory.category.capitalize %></div>
									<div class="col-2 text-center my-auto"><%= inventory.total_quantity %></div>
									<div class="col-2 text-center my-auto"><%= inventory.price_range %></div>
								</div>
								<div class="col-auto text-center inventory-actions d-flex my-auto">
									<div class="d-flex">
										<button class="btn btn-primary me-2 my-auto p-1 float-top" id="inventory-<%= inventory.id %>-edit">
											Edit
										</button>
										<%= button_to "Delete", inventory_path(inventory), method: :delete, data: { turbo_confirm: "Are you sure to archive this inventory?" }, class: "btn btn-danger my-auto inventory-delete p-1"%>
									</div>
									<div class="my-auto">
										<div class="material-icons" style="font-size: 2em" id="inventory-<%= inventory.id %>-icon">
											chevron_right
										</div>
									</div>
								</div>
							</div>	
							<div class="col row items-container d-flex mx-4 px-3" id="items-container-<%= inventory.id %>" style="transform: scale(0); max-height: 0;">
								<div class="col-12 d-flex justify-content-center">
									TODO: Filter by age group and expiration date

								</div>
								<% inventory.items.each do |item| %>
									<div class="col-auto my-3 item position-relative">
										<div class="col text-center "> 
											(<%= item.age_list.group %>) <%= item.age_list.name %>
										</div>
										Quantity: <%= item.quantity %>
										<br>
										Price: ₱<%= item.price %>
										<br>
										Expiry: <%= item.expiration_date %>	| <%= item.days_left %> days left
										<div class="position-absolute top-0 start-100 translate-middle">
											<%= button_to "X", inventory_item_path(item), method: :delete, data: { turbo_confirm: "Are you sure to remove this item?" }, class: "btn btn-danger px-1 py-0" %>
										</div>
									</div>
								<% end %>
								<%# link to add new item %>
								
								<div class="col-auto my-auto p-3 new-item" onclick="window.location.href='<%= new_inventory_item_path(inventory_id: inventory.id) %>'">	
									<div class="material-icons">add</div>
									ADD NEW ITEM
								</div>
							</div>
						</div>
					<% end %>
					<script>
						$(document).ready(function(){
							$('.inventory-row').click(function(){
								var id = $(this).attr('id');
								var items_container = $('#items-container-' + id.split('-')[1]);
								var icon_element = $('#inventory-' + id.split('-')[1] + '-icon');
								var edit_button = $('#inventory-' + id.split('-')[1] + '-edit');

								// Check if any other inventory-row is currently expanded
								var is_any_expanded = $('.inventory-row').filter(function() {
									return $(this).find('.items-container').css('transform') == 'matrix(1, 0, 0, 1, 0, 0)';
								}).length > 0;

								// Collapse other inventory-rows before expanding the current one
								if (is_any_expanded) {
									$('.inventory-row').each(function() {
										if ($(this).attr('id') != id && $(this).find('.items-container').css('transform') == 'matrix(1, 0, 0, 1, 0, 0)') {
											$(this).click();
										}
									});
								}

								if (items_container.css('transform') == 'matrix(1, 0, 0, 1, 0, 0)') {
									items_container.css('transform', 'scale(0)');
									items_container.css('max-height', '0');

									$(this).css('background-color', '');
									icon_element.css('transform', 'rotate(0deg)');
									edit_button.text('Edit');
									
								} else {
									items_container.css('transform', 'scale(1)');
									items_container.css('max-height', 'fit-content');

									$(this).css('background-color', '#e1e1e1');
									icon_element.css('transform', 'rotate(90deg)');
									edit_button.text('Close');
								}
							});
							$('.inventory-row .items-container').click(function(e){
								e.stopPropagation();
							});
							$('.inventory-row .inventory-delete').click(function(e){
								e.stopPropagation();
							});
						});
					</script>
				</div>
			</div>
		</div>
	</div>
	<div class="blank-space">
	</div>
	<div class="new-inventory p-3 me-4" onclick="location.href='<%= new_inventory_path %>'">
		<div class="d-flex justify-content-center">
			<div class="material-icons">add</div>
			ADD NEW INVENTORY
		</div>
	</div>
</div>

app/views/inventories/new.html.erb
<div class="inventory-new-page d-flex justify-content-center align-items-center" data-controller="inventories">
  <%= form_with model: @inventory, url: inventory_index_path, html: { class: "col-11 p-4"}  do |form| %>
    <%= form.fields_for :inventory_items do |item_form| %>
      <div class="text-center">  
        <h3>ADD NEW INVENTORY</h3>
      </div>
      <div class="row">
        <div class="col-6">
            <div class="custom-dropdown">
              <h5>Inventory Name: </h5>
              <%= form.text_field :name, class: 'form-control', id: 'inventory-name', autocomplete: 'off', required: true %>
              <div class="options" id="inventory-options">
                <% @unique_names.each do |name| %>
                  <div class="option"><%= name %></div>
                <% end %>
              </div>
            </div>
          <div class="custom-dropdown">
            <h5>Type:</h5>
            <%= form.text_field :inventory_type, class: "form-control", id: "inventory-type-name", autocomplete: 'off', placeholder: "Parvo Shot / Anti-Rabies / Deworm (etc.)", required: true %>
            <div class="options" id="inventory-type-options">
              <% @unique_inventory_types.each do |inventory_type| %>
                <div class="option"><%= inventory_type %></div>
              <% end %>
            </div>
          </div>
          <div class="custom-dropdown">
            <h5>Category</h5>
            <%= form.text_field :category, class: "form-control", id: "category-name", autocomplete: 'off', placeholder: "Dog / Cat / Cow (etc.)", required: true %>
            <div class="options" id="category-options">
              <% @unique_categories.each do |category| %>
                <div class="option"><%= category %></div>
              <% end %>
            </div>
          </div>
          <div>
            <h5 class="mb-2">Manufacturer</h5>
            <%= form.text_field :manufacturer, class: "form-control", autocomplete: 'off', placeholder: "Pfizer / Merck (etc.)" %>
          </div>
        </div>
        <div class="col-6">
          <div>
            <h5>Prescription (age):</h5>
            <div class="rpw d-flex prescription-container p-2 flex-column">
              <div class="col-12 d-flex">
                <div class="col-6">
                  <h5 class="text-center">YOUNG</h5>
                </div>
                <div class="col-6">
                  <h5 class="text-center">ADULT</h5>
                </div>
              </div>
              <div class="col-12 prescription-select  ">
                <%= item_form.collection_radio_buttons :age_list_id, @prescription_selection, :last, :first, {},  required: true, autocomplete: 'off' do |b| %>
                  <div class="col">
                    <%= b.radio_button class:"btn-check" %>
                    <%= b.label class:"btn btn-outline-success w-100" %>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-3">
          <h5>Quantity:</h5>
          <%= item_form.number_field :quantity, class: "form-control", min: 1, value: 1, required: true, autocomplete: 'off'%>
        </div>
        <div class="col-3">
          <h5>Price Each:</h5>
          <div class="input-group">
            <div class="input-group-prepend">
              <span class="input-group-text">PHP</span>
            </div>
            <%= item_form.number_field :price, class: "form-control", min: 0, step: 0.01, value: 10.00, required: true, autocomplete: 'off'%>
          </div>
        </div>
        <div class="col-3">
          <h5>Price total:</h5>
          <div class="input-group">
            <div class="input-group-prepend">
              <span class="input-group-text">PHP</span>
            </div>
            <%= item_form.text_field :price_total, class: "form-control", readonly: true, value: 10.00, autocomplete: 'off', disabled: true %>
          </div>
          <script type="text/javascript">
            $(document).ready(function(){
              $('#inventory_inventory_items_price').on('input', function() {
                var price = $('#inventory_inventory_items_price').val();
                var quantity = $('#inventory_inventory_items_quantity').val();
                var total = price * quantity;
                $('#inventory_inventory_items_price_total').val(total.toFixed(2));
              });
              $('#inventory_inventory_items_quantity').on('input', function() {
                var price = $('#inventory_inventory_items_price').val();
                var quantity = $('#inventory_inventory_items_quantity').val();
                var total = price * quantity;
                $('#inventory_inventory_items_price_total').val(total.toFixed(2));
              });
            });

          </script>
        </div>
        <div class="col-3">
          <h5>Expiration Date:</h5>
          <%= item_form.text_field :expiration_date    , placeholder: "Select Date", class: "form-control", required: true, autocomplete: 'off'%>
          <script type="text/javascript">
            $(function() {

              $('#inventory_inventory_items_expiration_date').daterangepicker({
                showDropdowns: true,
                // min date is set to today
                minDate: moment(),
                // max date is set to 5 years from now
                maxDate: moment().add(10, 'years'),
                
                autoUpdateInput: false,
                locale: {
                  format: 'MMM DD, YYYY'
                },
                singleDatePicker: true,
                // display at the center of the input
                drops: 'up'
                
                

              });

              
            
              $('#inventory_inventory_items_expiration_date').on('apply.daterangepicker', function(ev, picker) {
                $(this).val(picker.startDate.format('MMM DD, YYYY'));
              });

              $('#inventory_inventory_items_expiration_date').on('cancel.daterangepicker', function(ev, picker) {
                $(this).val('');
              });
              $('#inventory_inventory_items_expiration_date').on('keydown paste', function(e){
                e.preventDefault();
              });
            });
          </script>
        </div>
      </div>

    <% end %>
    <div class="py-3">
      <%= link_to "Cancel", inventory_index_path, class: "btn btn-danger" %>
      <%= form.submit "Add", class: "btn btn-success" %>
    </div>
  <% end %>
      
        

</div>

app/views/inventories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @inventory %>

<div>
  <%= link_to "Edit this inventory", edit_inventory_path(@inventory) %> |
  <%= link_to "Back to inventories", inventories_path %>

  <%= button_to "Destroy this inventory", @inventory, method: :delete %>
</div>