config/routes.rb
Rails.application.routes.draw do
  resources :vet_records
  root "home#index"
  resources :dogs
  resources :inventory, controller: 'inventories', as: 'inventory'
  resources :inventory_items
  resources :users do
    patch 'set_role', on: :member, as: :set_role
    patch 'restore', on: :member, as: :restore
  end
  resource :records, only: [:show]
  resources :first_login, only: [:index, :update]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  # Defines the root path route ("/")
  # root "articles#index"
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/register', to: 'users#new'  
  get '/scan', to: 'scan#index', as: 'scan'
  get '/data_export', to: 'data_export#index'
  get 'data_export/download_report'
  # get '/first_login', to: 'admin_approval#index', as: "first_login"
  # patch '/admin_approval/:id', to: 'admin_approval#update', as: 'first_login'
  get '/dashboard', to: 'dashboard#index' 
end

app/models/dog.rb
class Dog < ApplicationRecord
  
  has_paper_trail
  belongs_to :breed
  belongs_to :place
  belongs_to :user  
  has_and_belongs_to_many :dog_states
  has_and_belongs_to_many :vaccines
  has_and_belongs_to_many :conditions
  has_many :dog_pictures, dependent: :destroy
  # has one age list in AgeList model
  has_one :age_list, dependent: :destroy

  accepts_nested_attributes_for :dog_pictures, :allow_destroy => true

  def breed_name
    breed.name
  end

  def status
    dog_states.pluck(:name)
  end

  def location
    place.name
  end

  def sex
    gender ? "Male" : "Female"
  end
  
  def size_name
    size ? "Puppy" : "Adult"
  end

  def condition_names
    conditions.pluck(:name)
  end

  def disposed?
    condition_names.include?("Disposed")
  end

  def archive
    self.update(archived_at: Time.now)
  end

  def archived?
    archived_at?
  end

  def exp_neutered
    neutered ? "Yes" : "No"
  end

  def exp_sex
    gender ? "M" : "F"
  end

  def exp_date
    created_at.localtime.strftime("%b %d, %Y %I:%M %p")
  end

  def exp_age(age)
		years = age / 12
		remaining_months = age % 12
		if years > 0
		  if remaining_months > 0
			"#{years}yr #{remaining_months}mon"
		  else
			"#{years}yr"
		  end
		else
		  "#{remaining_months}mon"
		end

  end

  def exp_status(file_type)
    case file_type
    when "PDF"
      status.map { |x| [{ content: x, borders: [] }] }
    when "CSV"
      "\"#{status.join(", ")}\""
    when "Excel"
      status.join(", ")
    end
  end

  def exp_conditions(file_type)
    case file_type
    when "PDF"
      condition_names.map { |x| [{ content: x, borders: [] }] }
    when "CSV"
      "\"#{condition_names.join(", ")}\""
    when "Excel"
      condition_names.join(", ")
    end
  end

  def self.export(date_range, group, file_type)
    list = []
    case group
    when "all"
      list = self.where(created_at: date_range, archived_at: nil)
    when "healthy"
      list = self.where(created_at: date_range, archived_at: nil).joins(:conditions).where(conditions: { name: "Healthy" })
    when "operation"
      list = self.where(created_at: date_range, archived_at: nil).joins(:conditions).where(conditions: { name: "Operation" })
    when "disposed"
      list = self.where(created_at: date_range, archived_at: nil).joins(:conditions).where(conditions: { name: "Disposed" })
    end
    data = [ 
      ["Public ID", "Breed","Sex","Age","Neutered","Owner","Location", "Status", "Condition", "Date"] 
    ]
    list.each do |d|  
      data += [[d.public_id,d.breed_name,d.exp_sex,d.exp_age(d.age),d.exp_neutered,"N/A",d.location,d.exp_status(file_type),d.exp_conditions(file_type),d.exp_date]]
    end
    data
  end
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  include Authentication
  before_action :set_dog, only: %i[ show edit update destroy ]
  before_action :check_dop_presence, only: %i[ show edit update destroy ]

  # GET /dogs or /dogs.json
  def index
    redirect_to records_path
  end 

  # GET /dogs/1 or /dogs/1.json
  def show
    if @dog.archived?
      redirect_back fallback_location: records_path, flash: { alert: "Dog Profile was archived" }
    else
      @dog_images = @dog.dog_pictures.where(archived_at: nil) 
    end
  end

  # GET /dogs/new
  def new
    @dog = Dog.new
    @dog_images = @dog.dog_pictures.build
    @places = Place.pluck(:name,:id).sort
    @dog_states = DogState.pluck(:name,:id).sort
    @breeds = Breed.pluck(:name,:id).sort
    @conditions = Condition.pluck(:name,:id).sort
    @vaccines = Vaccine.pluck(:name,:id).sort
  end

  # GET /dogs/1/edit
  def edit
    @dog_images = @dog.dog_pictures.where(archived_at: nil)
    @places = Place.pluck(:name,:id).sort
    @dog_states = DogState.pluck(:name,:id).sort
    @breeds = Breed.pluck(:name,:id).sort
    @conditions = Condition.pluck(:name,:id).sort
    @vaccines = Vaccine.pluck(:name,:id).sort
  end

  # POST /dogs or /dogs.json
  def create
    @dog = Dog.new(dog_params)
    @dog.public_id = generate_public_id
    @dog.user = current_user
    if @dog.valid? && @dog.save
      params[:dog_images]['image'].each do |a|
        @dog_image = @dog.dog_pictures.create!(:image => a,:dog_id => @dog.id) unless a.blank?
      end
      @dog.versions.create!(event: "Create Dog", whodunnit: "#{current_user.username}")
      @dog.reload
      redirect_to dog_path(@dog.uuid), flash: { notice: "Successully Added Dog Profile" }
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /dogs/1 or /dogs/1.json
  def update
    if @dog.update(dog_params)
      dog_image = @dog.dog_pictures
      dog_image.each do |img|
        img.archive
      end
      params[:dog_images]['image'].each do |a|
        @dog_image = @dog.dog_pictures.create!(:image => a,:dog_id => @dog.id) unless a.blank?
      end
      @dog.versions.create!(event: "Update Dog", whodunnit: "#{current_user.username}")
      redirect_to dog_path(@dog.uuid), flash: { notice: "Successully Update Dog Profile" }
    else
      render :new, status: :unprocessable_entity
    end
  end 

  # DELETE /dogs/1 or /dogs/1.json
  def destroy
    @dog.archive
    @dog.versions.create!(event: "Archive Dog", whodunnit: "#{current_user.username}")
    redirect_to records_path, flash: { notice: "Successully Archive Dog Profile" }
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dog
      @dog = Dog.find_by(uuid: params[:id])
    end

    def check_dop_presence
      redirect_to records_path, flash: {alert: "Dog Profile not found"} unless @dog.present?
    end

    # Only allow a list of trusted parameters through.
    def dog_params
      params.require(:dog).permit(:breed_id, :place_id, :age, :gender, :size, :neutered, dog_images_attributes: [:id, :dog_id, :image], condition_ids: [], dog_state_ids: [],vaccine_ids: [])
    end

    def generate_public_id
      Time.now.strftime("%b%d%y") + "_" + ((SecureRandom.random_number(9e2) + 1e2).to_i).to_s
    end
end

app/helpers/dogs_helper.rb
module DogsHelper
    def dog_pic(pic,class_string="", style_string="")
        image_tag "data:#{pic.content_type};base64,#{to_base64(pic.read)}", class: class_string, style: style_string
    end
end

app/views/dogs/_dog.html.erb
<div class="dog-data col-11 mx-auto mt-2 d-flex flex-column ">
  <div id="DogImagesCarousel" class="carousel carousel-dark slide" data-bs-ride="carousel">
    <div class="carousel-indicators">
      <% @dog_images.count.times do |n|%>
        <% if n.zero? %>
          <%= button_tag("", type: "button", data: { bs_target: "#DogImagesCarousel", bs_slide_to: n.to_s }, "aria-label": "Slide #{(n+1).to_s}") %>
        <% else %>
          <%= button_tag("", type: "button", data: { bs_target: "#DogImagesCarousel", bs_slide_to: n.to_s }, class: "active", "aria-current": "true", "aria-label": "Slide #{(n+1).to_s}") %>  
        <% end %>
      <% end %>
    </div>
    <div class="carousel-inner h-100">
      <% @dog_images.each_with_index do |pic, idx| %>
        <div class="carousel-item h-100 <%= "active" if idx.zero? %>">
          <div class="d-flex justify-content-center h-100">
            <%= dog_pic(pic.image,"","#{"filter: grayscale(100%)" if @dog.disposed?}")%>
          </div>
        </div>
      <% end %>
    </div>
    <button class="dog-carousel-controller carousel-control-prev" type="button" data-bs-target="#DogImagesCarousel" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="dog-carousel-controller carousel-control-next" type="button" data-bs-target="#DogImagesCarousel" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
  <div class="dog-details flex-grow-1 d-flex flex-column align-items-center mx-5">
    <div class="col-12 d-flex justify-content-between">
      <div class="bg-secondary text-white border border-dark rounded-pill m-1 px-2" style="width:fit-content">ID: <%= @dog.public_id%></div>
      <div class="d-flex">
        <% if @dog.disposed? %>
          <div class="bg-black text-white rounded-pill m-1 px-2" style="width:fit-content">Disposed</div>
        <% else %>
          <% @dog.condition_names.each do |name|%>
            <%= status_condition_tags(name)%>
          <% end %>
        <% end %>
        
      </div>
    </div>
    <div class="row w-100 h-25 mt-3">
      <div class="col-6">

        <p class="fs-1 fw-bold">
          <%= @dog.sex %>
        </p>
      </div>
      <div class="col-6">
        <p class="float-end fs-2">
          <%= convert_to_years_months(@dog.age) %> 
        </p>
      </div>
    </div>
    <div class="row w-100 h-25">
      <div class="col-6">
        <p class="fs-2">
          <%= @dog.breed_name %>
        </p>
      </div>
      <div class="col-6">
        <p class="float-end fs-2">
          <%= @dog.location %>, Ormoc City
        </p>
      </div>
    </div>
    <div class="row w-100 h-50 fs-3">
      <div class="col-4">
      <p>Size: <%= @dog.size_name %></p>
      <p>Owner: (CUSTOMER FIRST NAME)</p>
      </div>
      <div class="col-4">
      <p>Date: <%= @dog.created_at.localtime.strftime("%b %d, %Y %I:%M %p") %></p>
      <p>Status: </p></div>
      <div class="col-4">
      <p>CONDITION:  </p>
      <p>veterinarian: (VET NAME)</p></div>
    </div>
  </div>
</div>

app/views/dogs/_edit_form.html.erb
<script>
  $(document).on('select2:open', () => {
    let allFound = document.querySelectorAll('.select2-container--open .select2-search__field');
    $(this).one('mouseup keyup',()=>{
      setTimeout(()=>{
        allFound[allFound.length - 1].focus();
      },0);
   });
});
</script>
<div id="drop-area" ondrop="handleDrop(event)" class="col-11 image-uploader position-relative mx-auto my-3" style="border-style: solid;">
  <div id="image-list" class="row mx-2 my-2 pb-4 flex-wrap">
    <% @dog_images.each do |pic|%>
      <div class="position-relative col-3 d-flex justify-content-center py-3" style="height:25vh;">
        <%= dog_pic(pic.image,"my-auto","object-fit: contain")%>
        <button class="position-absolute top-0 end-0 btn btn-danger" onclick="this.parentNode.remove()">X</button>
      </div>
    <% end %>
      <div class="col-3 d-flex align-items-center justify-content-center py-3" style="height:25vh;">
        <div class="add-new-photo col-10 h-75 d-flex justify-content-center align-items-center">
            <div class="material-icons fs-1">add_a_photo</div>
        </div>
      </div>
  </div>
  <div class="d-none material-icons upload-icon position-absolute top-50 start-50 translate-middle ">add_a_photo</div>
  <h3 class="d-none w-100 text-center position-absolute bottom-0 start-50 translate-middle-x">
    Drag and drop images here
  </h3>
</div>
<div class="col-12 m-3 " data-controller="dog-form">
  <%= form_with(model: @dog,url: dog_path(@dog.uuid),:html => { :multipart => true, :id => "id-dog-form"}) do |form| %>
    <div class="row w-100">
      <div class="form-floating col-6 py-4">
        <%= form.select :breed_id, @breeds,{prompt: ""},{required: 'true', autocomplete: 'off', class: 'form-select py-0', data: { placeholder: "Select Breed"}} %>
        <%= form.label "Breed"%> 
      </div>
      <div class="form-floating col-6 py-4">
        <%= form.select :place_id, @places,{prompt: ""},{required: 'true', autocomplete: 'off', class: 'form-select py-0', data: { placeholder: "Select Location"}} %>
        <%= form.label "Location"%> 
      </div>

      <div class="form-floating <%= ( current_user.admin? || current_user.frontliner? ) ? "col-4" : "col-6" %> py-4">
        <%= form.select :dog_state_ids,  @dog_states,{prompt: ""},{required: 'true', autocomplete: 'off', class: 'form-select py-0 w-100', multiple: true, data: { placeholder: "Select Statuses"}} %>
        <%= form.label "Status"%> 
      </div>
      <div class="form-floating <%= ( current_user.admin? || current_user.frontliner? ) ? "col-4" : "col-6" %> py-4">
        <%= form.select :condition_ids,  @conditions,{prompt: ""},{required: 'true', autocomplete: 'off', class: 'form-select py-0 w-100', multiple: true, data: { placeholder: "Select Conditions"}} %>
        <%= form.label "Conditions"%> 
      </div>
      <% if (current_user.admin? || current_user.frontliner?)%>
        <div class="form-floating col-4 py-4">
          <%= form.select :vaccine_ids,  @vaccines,{prompt: ""},{autocomplete: 'off', class: 'form-select py-0 w-100', multiple: true, data: { placeholder: "Select Vaccines"}} %>
          <%= form.label "Vaccines"%> 
        </div>
      <% end %>
      
      <div class="col-3 myauto">
        <%= form.label "Gender :", style: "display: inline" %>
        <%= form.check_box :gender, class: "switch pt-3",checked: @dog.gender, data: { toggle: "switch", on_color: "male", on_text: "Male", off_color: "female", off_text: "Female" } %>
      </div>
      <div class="col-3 myauto">
        <%= form.label "Size :", style: "display: inline" %>
        <%= form.check_box :size, class: "switch pt-3",checked: true, data: { toggle: "switch", on_color: "puppy", on_text: "Puppy", off_color: "adult", off_text: "Adult" }%>
      </div>
      <div class="col-3 myauto">
        <%= form.label "Neutered :", style: "display: inline" %>
        <%= form.check_box :neutered, class: "switch pt-3",checked: @dog.neutered, data: { toggle: "switch", on_color: "success", on_text: "Yes", off_color: "danger", off_text: "No" } %>
      </div>
      <div class="col-3 myauto">
        <%= form.label "Age :", style: "display: inline" %>
        <%= form.number_field :age, min: 0, max: 156, step: 1, value: @dog.age, style: "width: 50px" %> (in months)
      </div>
    </div>

    <div class='d-none'>
      <%= form.fields_for :dog_images do |p| %>
        <%= p.label :image %><br>
        <%= p.file_field :image, multiple: true, required: true, accept: "image/jpeg, image/png", id: "images", name:"dog_images[image][]", autocomplete: 'off'%>
    </div>
    <div>
      <button id="dog-form-presubmit" type="button" class="btn btn-primary mt-2">Submit</button>
      <%= form.submit "Submit" , id: "dog-form-submit",class: "d-none"%>
    </div>
    <% if @dog.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(@dog.errors.count, "error") %> prohibited this dog from being saved:</h2>

        <ul>
          <% @dog.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  <% end %>

</div>
      <% end %>

app/views/dogs/_form.html.erb
<script>
  var files = [];
  function handleDrop(event) {
    event.preventDefault();
    var newFiles = event.dataTransfer.files;
    for (var i = 0; i < newFiles.length; i++) {
      var file = newFiles[i];
      files.push(file);
    }
  }
</script>
<div id="drop-area" ondrop="handleDrop(event)" class="col-11 image-uploader position-relative mx-auto my-3">
  <div id="image-list" class="row m-3 pb-4 flex-nowrap"></div>
  <div class=" material-icons upload-icon position-absolute top-50 start-50 translate-middle ">add_a_photo</div>
  <h3 class=" w-100 text-center position-absolute bottom-0 start-50 translate-middle-x">
    Drag and drop images here
  </h3>
</div>
<div class="col-12 m-3 " data-controller="dog-form">
  <%= form_with(model: @dog,:html => { :multipart => true }) do |form| %>
    <div class="row w-100">
      <div class="form-floating col-6 py-4">
        <%= form.select :breed_id, @breeds,{prompt: "Select Breed"},{required: 'true', autocomplete: 'off', class: 'form-select py-0'} %>
        <%= form.label "Breed"%> 
      </div>
      <div class="form-floating col-6 py-4">
        <%= form.select :place_id, @places,{prompt: "Select Location"},{required: 'true', autocomplete: 'off', class: 'form-select py-0'} %>
        <%= form.label "Location"%> 
      </div>
      <div class="form-floating col-6 py-4">
        <%= form.select :dog_state_id,  @dog_states,{prompt: "Select Location"},{required: 'true', autocomplete: 'off', class: 'form-select py-0'} %>
        <%= form.label "Status"%> 
      </div>
      <div class="form-floating col-6 py-4">
        <%= form.select :condition_id,  @conditions,{prompt: "Select Condition"},{required: 'true', autocomplete: 'off', class: 'form-select py-0'} %>
        <%= form.label "Condition"%> 
      </div>
      <div class="col-4 myauto">
        <%= form.label "Gender :", style: "display: inline" %>
        <%= form.check_box :gender, class: "switch pt-3",checked: true, data: { toggle: "switch", on_color: "male", on_text: "Male", off_color: "female", off_text: "Female" }%>
      </div>
      <div class="col-4 myauto">
        <%= form.label "Neutered :", style: "display: inline" %>
        <%= form.check_box :neutered, class: "switch pt-3",checked: false, data: { toggle: "switch", on_color: "success", on_text: "Yes", off_color: "danger", off_text: "No" }%>
      </div>
      <div class="col-4 myauto">
        <%= form.label "Age :", style: "display: inline" %>
        <%= form.number_field :age, min: 0, max: 156, step: 1, value: 1, style: "width: 50px" %> (in months)
      </div>
    </div>

    <div>
      <%= form.fields_for :dog_images do |p| %>
        <%= p.label :image %><br>
        <%= p.file_field :image, multiple: true, required: true, accept: "image/jpeg, image/png", id: "images", name:"dog_images[image][]", autocomplete: 'off' %>
    </div>
    <div>
      <%= form.submit %>
    </div>
    <% if @dog.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(@dog.errors.count, "error") %> prohibited this dog from being saved:</h2>

        <ul>
          <% @dog.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  <% end %>

</div>
      <% end %>

app/views/dogs/_new_form.html.erb
<script>
  $(document).on('select2:open', () => {
    let allFound = document.querySelectorAll('.select2-container--open .select2-search__field');
    $(this).one('mouseup keyup',()=>{
      setTimeout(()=>{
        allFound[allFound.length - 1].focus();
      },0);
   });
});
</script>
<div id="drop-area" class="col-11 image-uploader position-relative mx-auto my-3">
  <div id="image-list" class="row m-3 pb-4 flex-wrap">
    
    <div class="d-none col-3 d-flex align-items-center justify-content-center py-3" style="height:25vh;">
      <div class="add-new-photo col-10 h-75 d-flex justify-content-center align-items-center">
          <div class="material-icons fs-1">add_a_photo</div>
      </div>
    </div>
  </div>
  <div class=" material-icons upload-icon position-absolute top-50 start-50 translate-middle ">add_a_photo</div>
  <h3 class=" w-100 text-center position-absolute bottom-0 start-50 translate-middle-x">
    Drag and drop images here
  </h3>
</div>
<div class="col-12 m-3 " data-controller="dog-form">
  <%= form_with(model: @dog,:html => { :multipart => true }) do |form| %>
    <div class="row w-100">
      <div class="form-floating col-6 py-4">
        <%= form.select :breed_id, @breeds,{prompt: ""},{required: 'true', autocomplete: 'off', class: 'form-select py-0', data: { placeholder: "Select Breed"}} %>
        <%= form.label "Breed"%> 
      </div>
      <div class="form-floating col-6 py-4">
        <%= form.select :place_id, @places,{prompt: ""},{required: 'true', autocomplete: 'off', class: 'form-select py-0', data: { placeholder: "Select Location"}} %>
        <%= form.label "Location"%> 
      </div>

      <div class="form-floating <%= ( current_user.admin? || current_user.frontliner? ) ? "col-4" : "col-6" %> py-4">
        <%= form.select :dog_state_ids,  @dog_states,{prompt: ""},{required: 'true', autocomplete: 'off', class: 'form-select py-0 w-100', multiple: true, data: { placeholder: "Select Statuses"}} %>
        <%= form.label "Status"%> 
      </div>
      <div class="form-floating <%= ( current_user.admin? || current_user.frontliner? ) ? "col-4" : "col-6" %> py-4">
        <%= form.select :condition_ids,  @conditions,{prompt: ""},{required: 'true', autocomplete: 'off', class: 'form-select py-0 w-100', multiple: true, data: { placeholder: "Select Conditions"}} %>
        <%= form.label "Conditions"%> 
      </div>
      <% if (current_user.admin? || current_user.frontliner?)%>
        <div class="form-floating col-4 py-4">
          <%= form.select :vaccine_ids,  @vaccines,{prompt: ""},{autocomplete: 'off', class: 'form-select py-0 w-100', multiple: true, data: { placeholder: "Select Vaccines"}} %>
          <%= form.label "Vaccines"%> 
        </div>
      <% end %>
      
      <div class="col-3 myauto">
        <%= form.label "Gender :", style: "display: inline" %>
        <%= form.check_box :gender, class: "switch pt-3",checked: true, data: { toggle: "switch", on_color: "male", on_text: "Male", off_color: "female", off_text: "Female" }%>
      </div>
      <div class="col-3 myauto">
        <%= form.label "Size :", style: "display: inline" %>
        <%= form.check_box :size, class: "switch pt-3",checked: true, data: { toggle: "switch", on_color: "puppy", on_text: "Puppy", off_color: "adult", off_text: "Adult" }%>
      </div>
      <div class="col-3 myauto">
        <%= form.label "Neutered :", style: "display: inline" %>
        <%= form.check_box :neutered, class: "switch pt-3",checked: false, data: { toggle: "switch", on_color: "success", on_text: "Yes", off_color: "danger", off_text: "No" }%>
      </div>
      <div class="col-3 myauto">
        <%= form.label "Age :", style: "display: inline" %>
        <%= form.number_field :age, min: 0, max: 156, step: 1, value: 1, style: "width: 50px" %> (in months)
      </div>
    </div>

    <div class='d-none'>
      <%= form.fields_for :dog_images do |p| %>
        <%= p.label :image %><br>
        <%= p.file_field :image, multiple: true, required: true, accept: "image/jpeg, image/png", id: "images", name:"dog_images[image][]", autocomplete: 'off' %>
    </div>
    <div class="w-100 d-flex align-items-center my-3 g-3">

      <%= link_to "Cancel", dashboard_path, class: "btn btn-danger me-3" %>
      <button id="dog-form-presubmit" type="button" class="btn btn-primary">Submit</button>
      <%= form.submit "Submit" , id: "dog-form-submit",class: "d-none"%>
    </div>
    <% if @dog.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(@dog.errors.count, "error") %> prohibited this dog from being saved:</h2>

        <ul>
          <% @dog.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  <% end %>

</div>
      <% end %>

app/views/dogs/edit.html.erb
<div class="dog-new-page">
  <div class="row w-100 h-100 g-0 d-flex flex-column flex-nowrap" style="border: 1px solid black;">
    <div class="title-container row g-0 flex-shrink-1">
      <div class="col-12 col-md-12 d-flex justify-content-between px-3 align-items-center" style="border: 1px solid black;">
        <div class="form-title p-1 rounded-pill ">
          <p class="fs-3 m-1 ">Edit Dog Profile</p>
        </div>
        <% if request.referrer %>
          <%= link_to "Back", :back, class: "btn btn-secondary" %>
        <% else %>
          <%= link_to "Back", records_path, class: "btn btn-secondary" %>
        <% end %>

      </div>
    </div>
    <div class="dog-form row g-0 h-100" style="border: 1px solid black;">
      <div class="col-12 overflow-scroll h-100" style="border: 1px solid black;">
        <div class=" col-12" style="padding-bottom: 10vh">
          <div class="the-form col-11 mt-2 mx-auto">
            <%= render 'edit_form' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/dogs/new.html.erb
<div class="dog-new-page">
  <div class="row w-100 h-100 g-0 d-flex flex-column flex-nowrap" style="border: 1px solid black;">
    <div class="title-container row g-0 flex-shrink-1">
      <div class="col-12 col-md-12 d-flex justify-content-between px-3 align-items-center" style="border: 1px solid black;">
        <div class="form-title p-1 mx-3 rounded-pill ">
          <p class="fs-3 m-1">Register New Dog</p>
        </div>
      </div>  
    </div>
    <div class="dog-form row g-0 h-100" style="border: 1px solid black;">
      <div class="col-12 overflow-scroll h-100" style="border: 1px solid black;">
        <div class=" col-12" style="padding-bottom: 10vh">
          <div class="the-form col-11 mt-2 mx-auto">
            <%= render 'new_form' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/dogs/show.html.erb
<div class="dog-show-page">
  <div class="row w-100 h-100 g-0 d-flex flex-column flex-nowrap">
    <div class="title-container row g-0 flex-shrink-1">
      <div class="col-12 col-md-12 d-flex px-3 justify-content-between">
        <div class="dog-title p-1 rounded-pill ">
          <p class="fs-3 m-1">Dog Profile</p>
        </div>
        <div class="d-flex align-items-center">
        <% if request.referrer && request.referrer.include?('dog_path') %>
          <%= link_to "Back", :back, class: "btn btn-secondary" %>
        <% else %>
          <%= link_to "Back", records_path, class: "btn btn-secondary" %>
        <% end %>
        <%= button_to "Edit Profile", edit_dog_path(@dog.uuid),method: :get, class: "btn btn-primary mx-2" if (current_user.admin? || current_user?(@dog.user)) %>
        <%= button_to "Archive Profile", dog_path(@dog.uuid),method: :delete, data: {turbo_confirm: 'Are you sure you want to archive this record?'}, class: "btn btn-danger" if (current_user.admin? || current_user?(@dog.user)) %>
        </div>
      </div>
    </div>
    <div class="dog-form row g-0 h-100" style="border: 1px solid black;">
      <div class="col-8 overflow-scroll h-100" style="border: 1px solid black;">
        <div class=" col-12" style="padding-bottom: 10vh">
          <div class="show-container col-12 mt-2  mx-auto">
            <%= render @dog %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>