config/routes.rb
Rails.application.routes.draw do
  resources :vet_records
  root "home#index"
  resources :dogs
  resources :inventory, controller: 'inventories', as: 'inventory'
  resources :inventory_items
  resources :users do
    patch 'set_role', on: :member, as: :set_role
    patch 'restore', on: :member, as: :restore
  end
  resource :records, only: [:show]
  resources :first_login, only: [:index, :update]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  # Defines the root path route ("/")
  # root "articles#index"
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/register', to: 'users#new'  
  get '/scan', to: 'scan#index', as: 'scan'
  get '/data_export', to: 'data_export#index'
  get 'data_export/download_report'
  # get '/first_login', to: 'admin_approval#index', as: "first_login"
  # patch '/admin_approval/:id', to: 'admin_approval#update', as: 'first_login'
  get '/dashboard', to: 'dashboard#index' 
end

app/models/user.rb
class User < ApplicationRecord
  has_paper_trail
  belongs_to :role, optional: true
  has_secure_password
  mount_uploader :profile_image, ProfileImageUploader
  has_many :vet_records, foreign_key: :created_by_user_id


  validates :name, presence: true, format: { with: /\A[ A-Za-z\.]+\z/i }
  validates :username, presence: true, :uniqueness => { case_sensitive: false }, format: { with: /\A[a-z0-9_\.]+\z/i }
  validates :password, presence: true, confirmation: true, length: { minimum: 8, maximum: 30},  unless: proc { |x| x.password.blank? }
  validate  :validate_image_type
  
  def approved_user?
    approved_at?
  end

  def approved_user!
    self.update(approved_at: Time.now)
  end

  def admin?
    type == "admin"
  end

  def admin!
    self.update(role_id: Role.find_by(name: "admin").id)
  end

  def type
    role.name
  end

  def encoder?
    type == "Encoder"
  end

  def encoder!
    self.update(role_id: Role.find_by(name: "Encoder").id)
  end

  def frontliner?
    type == "Frontliner"
  end

  def frontliner!
    self.update(role_id: Role.find_by(name: "Frontliner").id)
  end

  def archive
    self.update(archived_at: Time.now)
  end

  def archived?
    archived_at?
  end

  def setrole(id)
    self.update(role_id: id)
  end

  def total_logs
    versions.where(whodunnit: username).count
  end

  def first_loggedin?
    first_login_at?
  end
  
  def reset_user
    self.update(password: "Ormocanon", first_login_at: nil)
  end

  def restore_user
    self.update(archived_at: nil)
    self.reset_user
  end

  def doctor?
    type == "Doctor"
  end

  def doctor!
    self.update(role_id: Role.find_by(name: "Doctor").id)
  end

  def staff?
    type == "Staff"
  end

  def staff!
    self.update(role_id: Role.find_by(name: "Staff").id)
  end
  


  private

  def validate_image_type
    if profile_image.cached?
      if !profile_image.content_type.in?(%w(image/jpeg image/png))
        errors.add(:profile_image, 'must be a JPEG or PNG')
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
include Authentication

  before_action :set_user, only: %i[ show edit update destroy set_role restore]
  before_action :DoctorAccessable!, only: [:new, :create, :index, :destroy, :set_role, :restore]

  # GET /users or /users.json
  def index
    @users = User.all
    @roles = Role.pluck(:name,:id).sort
    @roles = @roles.reject{|role| role[0] == "admin"} unless current_user.admin?
    @approved_users = @users.where(archived_at: nil).where.not(approved_at: nil)
    @archived_users = @users.where.not(archived_at: nil)
    @approved_users = @approved_users.sort_by{|user| user == current_user ? 0 : 1}
    @approved_users = [@approved_users.first] + @approved_users.drop(1).sort_by(&:created_at)
    @approved_users = @approved_users.reject{|user| user.admin?}
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
      @user = User.new
      @roles = Role.pluck(:name,:id).sort
      @roles = @roles.reject{|role| role[0] == "admin"} unless current_user.admin?
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)
    @roles = Role.pluck(:name,:id).sort
    @user.password = "Ormocanon"
    if @user.valid? && @user.save
      @user.approved_user!
      @user.versions.create!(event: "Create User", whodunnit: "#{current_user.username}")
      redirect_to users_path , notice: "User Created Successully"
    else
      render :new, status: :unprocessable_entity
    end
  end
  # PATCH/PUT /users/1 or /users/1.json
  def update
    if @user.update(user_params)
      redirect_to (request.referrer || dashboard_path), notice: "Profile Image Updated"
    else
      redirect_to (request.referrer || dashboard_path), alert: "Image must be a JPEG or PNG"
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    unless current_user?(@user)
      @user.archive
      @user.versions.create!(event: "Archive User", whodunnit: "#{current_user.username}")
      redirect_to users_path, flash: { notice: "Successully Archive User" }
    else
      redirect_to users_path, flash: { alert: "Archive Yourself is not allowed" }
    end
  end

  def set_role
    @user.setrole(params[:user][:role_id])
    @user.versions.create!(event: "Set User Role,#{@user.type}", whodunnit: "#{current_user.username}")
    redirect_to users_path, flash: { notice: "Changed User Role" }
  end

  def restore
    @user.restore_user
    @user.versions.create!(event: "User Restore", whodunnit: "#{current_user.username}")
    redirect_to users_path, flash: { notice: "User Restored and Set to Default Password" }
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :username, :password, :password_confirmation, :profile_image, :role_id)
    end

    def DoctorAccessable!
      unless current_user.doctor? || current_user.admin?
        redirect_to dashboard_path, alert: "Unauthorized Action"
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :username, style: "display: block" %>
    <%= form.text_field :username %>
  </div>

  <div>
    <%= form.label :password, style: "display: block" %>
    <%= form.password_field :password %>
  </div>

  <div>
    <%= form.label :password_confirmation, style: "display: block" %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div>
    <%= form.label :role_id, style: "display: block" %>
    <%= form.text_field :role_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<div class="users-page" >
	<div class="col-12 row g-0 h-75">
		<div class="users-container col-12 h-100 px-2" >
			<div class="col-12 p-2 d-flex justify-content-between">
				<div>All Users</div>
			</div>
			<div class="col-12 h-100 overflow-scroll" >
				<table class="table">
					<thead>
						<tr>
							<th scope="col">USERNAME</th>
							<th scope="col">TOTAL LOGS</th>
							<%# <th scope="col">OWNER</th> %>
							<th scope="col">USER TYPE</th>
							<th scope="col">DATE CREATED</th>
							<th scope="col"></th>
						</tr>
					</thead>
					<tbody>
						<% @approved_users.each do |user|
							
						%>
							<tr>
								<td class="normal-user"><%= user.username %></td>
								<td class="normal-user"><%= user.total_logs %></td>
								<td class="normal-user">
                                    <% unless user.admin? || current_user?(user)%>
                                        <%= form_with model: user, url: set_role_user_path(user), method: :patch do |form| %>
                                            <%= form.select :role_id, @roles,{prompt: "Unset"},{required: 'true', autocomplete: 'off',onchange: "this.form.submit()"}%>
                                        <% end %>
                                    <% else %>
                                        <%= user.type.capitalize%>
                                    <% end %>
                                </td>
								<%# <td class="normal-user"><%= user.type.capitalize</td> %>
								<td class="normal-user"><%= user.created_at.localtime.strftime("%b %d, %Y") %></td>
								<td class="normal-user">
									<div class="d-flex flex-row me-2 justify-content-center">
										<%= button_to "Show", user_path(user),method: :get, class: "btn btn-info me-1" %>
										<%= button_to "Archive User", user_path(user),method: :delete,data: {turbo_confirm: 'Are you sure you want to archive this user?'}, class: "btn btn-danger" unless  user.admin? || current_user?(user) %>
									</div>
								</td>
							</tr>
						<% end %>
						<% unless @archived_users.blank? %>
							<tr>
								<td colspan="5" class="fs-5 archive-subheaders">
									Archived Users
								</td>
							</tr>
						<% end %>
						<% @archived_users.each do |user|%>
							<tr>
								<td class="archived-user"><%= user.username %></td>
								<td class="archived-user"><%= user.total_logs %></td>
								<td class="archived-user"><%= user.type %></td>
								<%# <td class="archived-user"><%= user.type.capitalize</td> %>
								<td class="archived-user"><%= user.created_at.localtime.strftime("%b %d, %Y") %></td>
								<td class="archived-user">
									<div class="d-flex flex-row me-2 justify-content-center">
										<%= button_to "Show", user_path(user),method: :get, class: "btn btn-info me-1" %>
										<%= button_to "Restore User", restore_user_path(user),method: :patch,data: {turbo_confirm: 'Are you sure you want to restore this user?'}, class: "btn btn-primary" unless current_user?(user) %>
									</div>
								</td>
							</tr>
						<% end %>
						<tr>
							<td colspan="5" ></td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>
	</div>
	<div class="new-user p-3 me-4 mb-4	" onclick="location.href='<%= register_path %>'">
		<div class="d-flex justify-content-center">
			<div class="material-icons">add</div>
			ADD NEW USER
		</div>
	</div>
</div>

app/views/users/new.html.erb
<div class="register-page">
  <div class="col-12 h-100 d-flex justify-content-center align-items-center">
	<div class="register-container p-4 ">
		<%= form_for @user, url: users_path do |f| %>
			<h2>CREATE USER</h2>
			<%= f.text_field :name, placeholder: "Full Name", autocomplete: 'off', required: true %>

			<%= f.text_field :username, placeholder: "Username", autocomplete: 'off', required: true %>

			<%= f.select :role_id, @roles,{prompt: "Select Type"},{required: 'true', autocomplete: 'off', class: ""}%>

			<div>Default password is "Ormocanon".	</div>
			<div>User can change the password after first login.</div>
			<%# f.password_field :password, placeholder: "Password", autocomplete: 'off', required: true %>

      		<%# f.password_field :password_confirmation, placeholder: "Retype Password", autocomplete: 'off', required: true  %>

			<%= f.submit "Submit" %>
			<% if @user.errors.any? %>
				<% @user.errors.full_messages.each do |message| %>
					<p><%= message %></p>
				<% end %>
			<% end %>
		<% end %>
	</div>
  </div>
</div>

app/views/users/show.html.erb
<div class="users-show-page p-3">
  <div>
    <h1 class="text-center">User Profile</h1>
    <div class="row">
      <div class="col-md-10 offset-md-1">
        <div class="card">
          <div class="card-body">
            <div class="row">
              <div class="col-md- 4">
                <img <%= has_profile_image("img") %> class="" alt="User Image">
              </div>
              <div class="col-md-8">
                <h3><%= @user.name %></h3>
                <p><%= @user.created_at.strftime("%B %d, %Y") %></p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>