config/routes.rb
Rails.application.routes.draw do
  resources :vet_records
  root "home#index"
  resources :dogs
  resources :inventory, controller: 'inventories', as: 'inventory'
  resources :inventory_items
  resources :users do
    patch 'set_role', on: :member, as: :set_role
    patch 'restore', on: :member, as: :restore
  end
  resource :records, only: [:show]
  resources :first_login, only: [:index, :update]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  # Defines the root path route ("/")
  # root "articles#index"
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/register', to: 'users#new'  
  get '/scan', to: 'scan#index', as: 'scan'
  get '/data_export', to: 'data_export#index'
  get 'data_export/download_report'
  # get '/first_login', to: 'admin_approval#index', as: "first_login"
  # patch '/admin_approval/:id', to: 'admin_approval#update', as: 'first_login'
  get '/dashboard', to: 'dashboard#index' 
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if current_user
      redirect_to dashboard_path
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_logo.html.erb
<div class="logo">

  <%= link_to root_path do %>
    <%= image_tag 'logo 1.png' %>
    OCVOM
  <% end %>
</div>

app/views/home/index.html.erb
<div class="home">
  <%= render "logo" %>
  <div class="home-i">
    <h1>ANIMAL CARE</h1>
    <p class="my-auto">Get your pets special treatment from our trusted veterinarians</p>
    <div class="home-i-b">
      <%= button_to "Login Portal", login_path, method: :get%>
      <%# <%= button_to "Register", register_path, method: :get%>
    </div>
  </div>
</div>


  